const $=id=>document.getElementById(id);
const charts=[{title:'PV · 400 hPa',base:'ecm0125_nat_gh400_pv400',ext:'png',start:0},{title:'Jet · 300 hPa',base:'ecm0125_nat_gh300_uv300',ext:'png',start:0},{title:'Geopotential · 500 hPa',base:'ecm0125_nat_gh500_gh500-1000',ext:'png',start:0},{title:'MSLP · T850 · 6h precipitation',base:'ecm0125_nat_msl_t850_6urk',ext:'jpg',start:6}];
const consistencyCharts={
 pv:charts[0],
 mslp:charts[3],
 height500:{...charts[2],title:'500 hPa height · thickness'},
 jet300:{...charts[1],title:'300 hPa jet · height'},
 humidity700:{title:'700 hPa humidity · vertical motion',base:'ecm0125_nat_r700_w700_uv700_gh700_gh700-1000',ext:'png',start:0}
};
$('consistency-chart').replaceChildren(...Object.entries(consistencyCharts).map(([value,chart])=>{
 const option=document.createElement('option');option.value=value;option.textContent=chart.title;return option;
}));
let view='overview',timer=null;
const pad=(n,size=2)=>String(n).padStart(size,'0');
const fmt=d=>`${d.toISOString().slice(0,10)} · ${pad(d.getUTCHours())}Z`;
function url(init,chart,h){const day=init.toISOString().slice(0,10),run=pad(init.getUTCHours());return `https://spakort.vedur.is/kort/ecm0125/${day.replaceAll('-','/')}/${run}/${chart.base}_${day.replaceAll('-','')}${run}_${pad(h,3)}.${chart.ext}`;}
for(let h=0;h<=240;h+=6){const option=document.createElement('option');option.value=h;option.textContent=`+${pad(h,3)}h`;$('hour').append(option);}
const now=new Date();$('date').value=now.toISOString().slice(0,10);$('run').value=now.getUTCHours()>=18?'12':'00';$('hour').value='24';
function state(){return {view,date:$('date').value,run:$('run').value,hour:Number($('hour').value)};}

function expandChart(title,src,img){$('zoom-title').textContent=title;$('zoom-image').hidden=false;$('zoom-image').src=img.currentSrc||img.src||src;$('zoom-image').alt=title;$('zoom').showModal();}

function panel(title,meta,src,unavailable){const article=document.createElement('article');article.className='panel';const head=document.createElement('div');head.className='panel-head';const labels=document.createElement('div');const heading=document.createElement('h2');heading.textContent=title;const details=document.createElement('div');details.className='metadata';details.textContent=meta;labels.append(heading,details);head.append(labels);const frame=document.createElement('div');frame.className='frame';const status=document.createElement('div');status.className='status';const strong=document.createElement('strong');strong.textContent=unavailable?'Outside forecast range':'Loading chart…';const message=document.createElement('span');message.textContent=unavailable||'';status.append(strong,message);frame.append(status);
 if(src){const actions=document.createElement('div');actions.className='actions';const expand=document.createElement('button');expand.textContent='Expand';expand.addEventListener('click',()=>{expandChart(`${title} · ${meta}`,src,img);});const link=document.createElement('a');link.textContent='Source';link.href=src;link.target='_blank';link.rel='noopener';actions.append(expand,link);head.append(actions);const img=document.createElement('img');img.alt=`${title} — ${meta}`;img.hidden=true;img.onload=()=>{status.hidden=true;img.hidden=false;};img.onerror=()=>{strong.textContent='Chart unavailable';message.textContent='This frame may not be published yet or may no longer be retained by the provider. Try an earlier run or another forecast hour.';};img.src=src;frame.append(img);}
 article.append(head,frame);$('grid').append(article);}
function render(){SatelliteLoops.pauseAll();$('context').hidden=view==='consistency';$('consistency-chart-control').hidden=view!=='consistency';document.body.classList.toggle("radar-view",view==="radar");$("radar-controls").hidden=view!=="radar";if(view==="radar"){stop();renderRadar();return;}stopRadar();if(!$('date').value||!$('date').checkValidity())return;const s=state(),init=new Date(`${s.date}T${s.run}:00:00Z`);if(!Number.isFinite(init.getTime()))return;const valid=new Date(init.getTime()+s.hour*3600000);$('initialized').textContent=fmt(init);$('valid').textContent=fmt(valid);$('lead').textContent=`+${pad(s.hour,3)} hours`;$('slider').value=s.hour;$('grid').replaceChildren();$('grid').className='grid'+(view==='water'?' water':'');document.querySelectorAll('[data-step]').forEach(b=>b.disabled=s.hour+Number(b.dataset.step)<0||s.hour+Number(b.dataset.step)>240);
 if(view==='overview'){$('context').textContent='Four fields at one forecast time. Precipitation starts at +006h; its actual valid time is shown when +000h is selected.';charts.forEach(c=>{const h=Math.max(c.start,s.hour);panel(c.title,`+${pad(h,3)}h · Valid ${fmt(new Date(init.getTime()+h*3600000))}`,url(init,c,h));});}
 if(view==='consistency'){
  const chart=consistencyCharts[$('consistency-chart').value]||consistencyCharts.pv;
  $('context').textContent='';
  [0,12,24,36].forEach(back=>{
   const r=new Date(init.getTime()-back*3600000),h=s.hour+back;
   const unavailable=h<chart.start?'This chart starts at +006h. Select a later valid time.':h>240?'This run would require a forecast beyond +240h. Select an earlier valid time.':null;
   panel(back?`Previous run · −${back}h`:'Selected run',`${chart.title} · ${fmt(r)} · +${pad(h,3)}h`,unavailable?null:url(r,chart,h),unavailable);
  });
 }
 if(view==='water'){$('context').textContent='WV uses individual 10-minute observations. Satellite playback is independent of the selected forecast valid time.';panel('Forecast PV · 400 hPa',`Valid ${fmt(valid)} · +${pad(s.hour,3)}h`,url(init,charts[0],s.hour));const wv=observationPanel('Observed water vapour','wv-image','https://modeles20.meteociel.fr/satellite/latestsatwvmtgalt.png');SatelliteLoops.mount(wv,'wv');}}
function step(delta){$('hour').value=String(Math.max(0,Math.min(240,Number($('hour').value)+delta)));render();}
function stop() {clearInterval(timer);timer=null;$('loop').textContent='Play loop';$('loop').setAttribute('aria-pressed','false');}
function play(){timer=setInterval(()=>{const h=Number($('hour').value);$('hour').value=String(h>=240?0:h+6);render();},Number($('speed').value));$('loop').textContent='Pause loop';$('loop').setAttribute('aria-pressed','true');}
document.querySelectorAll('[data-view]').forEach(b=>b.addEventListener('click',()=>{view=b.dataset.view;document.querySelectorAll('[data-view]').forEach(t=>t.setAttribute('aria-pressed',String(t===b)));render();}));document.querySelectorAll('[data-step]').forEach(b=>b.addEventListener('click',()=>step(Number(b.dataset.step))));['date','run','hour','consistency-chart'].forEach(id=>$(id).addEventListener('change',render));$('slider').addEventListener('input',()=>{$('hour').value=$('slider').value;render();});$('load').addEventListener('click',render);$('loop').addEventListener('click',()=>timer?stop():play());$('speed').addEventListener('change',()=>{if(timer){stop();play();}});$('close-zoom').addEventListener('click',()=>$('zoom').close());document.addEventListener('keydown',e=>{if(e.altKey||e.ctrlKey||e.metaKey||e.shiftKey||e.target.isContentEditable||['INPUT','SELECT','TEXTAREA'].includes(e.target.tagName)||$('zoom').open)return;if(e.target.tagName==='BUTTON'&&!document.body.classList.contains('controls-hidden'))return;if(e.key==='ArrowLeft'||e.key==='ArrowRight'){e.preventDefault();if(view==='radar')radarStep(e.key==='ArrowLeft'?-1:1);else step(e.key==='ArrowLeft'?-6:6);}});document.addEventListener('visibilitychange',()=>{if(document.hidden)stop();});

let radarFrames=[],radarIndex=0,radarTimer=null,radarRequest=null,radarRefresh=null;
const radarBase='https://cdn.fmi.fi/demos/eumetnet-web-site-radar-animator/';
function stopRadar(){clearInterval(radarTimer);radarTimer=null;clearInterval(radarRefresh);radarRefresh=null;$('radar-play').textContent='Play radar';$('radar-play').setAttribute('aria-pressed','false');}
function showRadarFrame(){const frame=radarFrames[radarIndex];if(!frame||view!=='radar')return;const img=$('radar-image');if(!img)return;img.src=frame.url;img.alt='OPERA CIRRUS radar composite · '+new Date(frame.epoch).toISOString();$('radar-time').textContent=new Date(frame.epoch).toISOString().replace('T',' · ').slice(0,21)+' UTC';$('radar-slider').max=String(radarFrames.length-1);$('radar-slider').value=String(radarIndex);$('radar-back').disabled=radarIndex===0;$('radar-next').disabled=radarIndex===radarFrames.length-1;}
async function refreshRadar(){if(radarRequest)return radarRequest;radarRequest=(async()=>{try{const response=await fetch(radarBase+'list-images/',{cache:'no-store',signal:AbortSignal.timeout(15000)});if(!response.ok)throw Error('Feed unavailable');const data=await response.json();const frames=(data.images||[]).filter(f=>Number.isFinite(f.epoch)&&typeof f.url==='string'&&f.url.startsWith(radarBase+'new-images/')).sort((a,b)=>a.epoch-b.epoch).slice(-36);if(!frames.length)throw Error('No radar frames');radarFrames=frames;radarIndex=frames.length-1;showRadarFrame();if(view==='radar')$('context').textContent='Radar: 5-minute observations · feed checked every 2 minutes. IR uses independent 10-minute observations. Zoom with + / − or the wheel; drag to pan; Fit restores Europe.';}catch{if(view==='radar')$('context').textContent=radarFrames.length?'Radar refresh failed; showing previously loaded observations. Try Refresh radar or the EUMETNET source.':'Radar feed unavailable. Try Refresh radar or open the EUMETNET source.';}finally{radarRequest=null;}})();return radarRequest;}
const irSource='https://modeles20.meteociel.fr/satellite/latestsatirmtgalt.png';
function observationPanel(title,id,source){const article=document.createElement('article');article.className='panel';const head=document.createElement('div');head.className='panel-head';const heading=document.createElement('h2');heading.textContent=title;head.append(heading);const tools=document.createElement('div');tools.className='image-tools';const frame=document.createElement('div');frame.className='frame zoomable';const img=document.createElement('img');img.id=id;img.alt=title;img.draggable=false;frame.append(img);let scale=1,x=0,y=0,drag=null;const indicator=document.createElement('span');indicator.textContent='1×';indicator.setAttribute('aria-live','polite');
function apply(){const width=frame.clientWidth||0,height=frame.clientHeight||0;const fit=img.naturalWidth&&img.naturalHeight?Math.min(width/img.naturalWidth,height/img.naturalHeight):1;const maxX=Math.max(0,((img.naturalWidth||width)*fit*scale-width)/2),maxY=Math.max(0,((img.naturalHeight||height)*fit*scale-height)/2);x=Math.max(-maxX,Math.min(maxX,x));y=Math.max(-maxY,Math.min(maxY,y));img.style.transform='translate('+x+'px,'+y+'px) scale('+scale+')';indicator.textContent=Number(scale.toFixed(1))+'×';frame.style.cursor=scale>1?'grab':'default';minus.disabled=scale<=1;plus.disabled=scale>=6;}
function changeZoom(value){scale=Math.max(1,Math.min(6,value));apply();}
const minus=document.createElement('button');minus.textContent='−';minus.setAttribute('aria-label','Zoom out '+title);minus.disabled=true;minus.addEventListener('click',()=>changeZoom(scale/1.4));const plus=document.createElement('button');plus.textContent='+';plus.setAttribute('aria-label','Zoom in '+title);plus.addEventListener('click',()=>changeZoom(scale*1.4));const reset=document.createElement('button');reset.textContent='Fit';reset.setAttribute('aria-label','Reset '+title+' to full view');reset.addEventListener('click',()=>{x=0;y=0;changeZoom(1);});const sourceLink=document.createElement('a');sourceLink.href=source;sourceLink.target='_blank';sourceLink.rel='noopener';sourceLink.textContent='Source';tools.append(minus,indicator,plus,reset,sourceLink);head.append(tools);
frame.addEventListener('wheel',e=>{e.preventDefault();changeZoom(scale*(e.deltaY<0?1.15:1/1.15));},{passive:false});frame.addEventListener('pointerdown',e=>{if(scale<=1||e.button!==0)return;drag={id:e.pointerId,startX:e.clientX,startY:e.clientY,x,y};frame.setPointerCapture(e.pointerId);frame.style.cursor='grabbing';});frame.addEventListener('pointermove',e=>{if(!drag||drag.id!==e.pointerId)return;x=drag.x+e.clientX-drag.startX;y=drag.y+e.clientY-drag.startY;apply();frame.style.cursor='grabbing';});function finish(){drag=null;frame.style.cursor=scale>1?'grab':'default';}frame.addEventListener('pointerup',finish);frame.addEventListener('pointercancel',finish);img.onload=apply;article.append(head,frame);$('grid').append(article);return img;}
function renderRadar(){$('grid').replaceChildren();$('grid').className='grid radar';$('context').textContent='Zoom with + / − or the mouse wheel; drag to pan; Fit restores Europe. Radar playback controls only the radar; IR has separate frame-by-frame playback.';const img=observationPanel('OPERA radar · CIRRUS','radar-image','https://www.eumetnet.eu/observations/opera-radar-animation/');img.onerror=()=>{$('context').textContent='Radar image unavailable; try another frame or Refresh radar.';};const ir=observationPanel('Infrared satellite · Meteociel','ir-image',irSource);ir.onerror=()=>{$('context').textContent='Infrared image unavailable; try Refresh radar or open its Source link.';};SatelliteLoops.mount(ir,'ir');if(radarFrames.length)showRadarFrame();void refreshRadar();if(!radarRefresh)radarRefresh=setInterval(()=>{if(view==='radar'&&!document.hidden){void refreshRadar();void SatelliteLoops.refresh('ir');}},120000);}

$('radar-play').addEventListener('click',()=>{if(radarTimer){clearInterval(radarTimer);radarTimer=null;$('radar-play').textContent='Play radar';$('radar-play').setAttribute('aria-pressed','false');return;}if(!radarFrames.length)return;radarTimer=setInterval(()=>{radarIndex=(radarIndex+1)%radarFrames.length;showRadarFrame();},500);$('radar-play').textContent='Pause radar';$('radar-play').setAttribute('aria-pressed','true');});
function radarStep(delta){clearInterval(radarTimer);radarTimer=null;$('radar-play').textContent='Play radar';$('radar-play').setAttribute('aria-pressed','false');radarIndex=Math.max(0,Math.min(radarFrames.length-1,radarIndex+delta));showRadarFrame();}
$('radar-back').addEventListener('click',()=>radarStep(-1));$('radar-next').addEventListener('click',()=>radarStep(1));$('radar-latest').addEventListener('click',()=>{radarIndex=radarFrames.length-1;radarStep(0);});$('radar-reload').addEventListener('click',()=>{void refreshRadar();void SatelliteLoops.refresh('ir');});$('radar-slider').addEventListener('input',()=>{radarIndex=Number($('radar-slider').value);radarStep(0);});document.addEventListener('visibilitychange',()=>{if(document.hidden)stopRadar();else if(view==='radar'){void refreshRadar();radarRefresh=setInterval(()=>void refreshRadar(),120000);}});

if(document.modelContext?.registerTool){try{Promise.resolve(document.modelContext.registerTool({name:'configure_ec_analysis',description:'Set the visible EC analysis view, model initialization and forecast lead.',inputSchema:{type:'object',properties:{view:{type:'string',enum:['overview','consistency','water','radar']},date:{type:'string',pattern:'^\\d{4}-\\d{2}-\\d{2}$'},run:{type:'string',enum:['00','12']},hour:{type:'integer',minimum:0,maximum:240,multipleOf:6}},required:['view','date','run','hour'],additionalProperties:false},annotations:{readOnlyHint:false},execute(input){if(!input||!['overview','consistency','water','radar'].includes(input.view)||!['00','12'].includes(input.run)||!Number.isInteger(input.hour)||input.hour<0||input.hour>240||input.hour%6||!/^\d{4}-\d{2}-\d{2}$/.test(input.date)||!Number.isFinite(Date.parse(input.date+'T00:00:00Z'))||new Date(input.date+'T00:00:00Z').toISOString().slice(0,10)!==input.date)throw new Error('Invalid analysis configuration');stop();$('date').value=input.date;$('run').value=input.run;$('hour').value=String(input.hour);document.querySelector(`[data-view="${input.view}"]`).click();return {...state(),validTime:$('valid').textContent};}})).catch(()=>{});}catch{}}
$('toggle-controls').addEventListener('click',()=>{
 const hidden=document.body.classList.toggle('controls-hidden');
 $('toggle-controls').textContent=hidden?'Show controls':'Hide controls';
 $('toggle-controls').setAttribute('aria-expanded',String(!hidden));
});
render();

